version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: ./gradlew clean build

      - store_test_results:
          path: build/test-results

      - store_artifacts:
          path: build/reports/tests/test
          destination: test_result

      - store_artifacts:
          path: build/reports/jacoco
          destination: test_coverage
